services:
  - type: web
    name: image-colorizer-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        sync: false
      - key: MAX_DIMENSION
        value: "2048"
      - key: MAX_FILE_SIZE
        value: "10485760"
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: model-storage
      mountPath: /opt/render/project/src/model
      sizeGB: 1 